# cloudbuild.yaml — Build Docker image -> Push Artifact Registry -> Deploy Cloud Run (with Secret Manager)

substitutions:
  _REGION: asia-southeast1
  _SERVICE: bvx-api
  _REPO: cloud-run-source-deploy
  _DB_INSTANCE: bvx-zalo-app-32f90:asia-southeast1:bvx-postgres
  _SA_EMAIL: bvx-zalo-app-32f90@appspot.gserviceaccount.com

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1) Build image từ Dockerfile ở thư mục gốc
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$SHORT_SHA'
      - '.'

  # 2) Push image lên Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$SHORT_SHA'

  # 3) Deploy Cloud Run bằng image vừa push
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE
      - --project=$PROJECT_ID
      - --region=$_REGION
      - --image=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$SHORT_SHA
      - --allow-unauthenticated
      - --service-account=$_SA_EMAIL
      - --add-cloudsql-instances=$_DB_INSTANCE

      # Secrets: dùng đúng secret đang có
      - --set-secrets=PGPASSWORD=DB_BVX_KEY:latest,API_KEY=DB_API_KEY:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest

      # Env không nhạy cảm: dùng user kpi_user + DB kpi_db
      - --set-env-vars=PGHOST=/cloudsql/bvx-zalo-app-32f90:asia-southeast1:bvx-postgres,PGPORT=5432,PGUSER=kpi_user,PGDATABASE=kpi_db

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$SHORT_SHA'
