# cloudbuild.yaml — build Docker image, push to Artifact Registry, deploy Cloud Run
substitutions:
  _REGION: asia-southeast1
  _SERVICE: bvx-api
  _REPO: cloud-run-source-deploy               # tên repo Artifact Registry (đã có)
  _DB_INSTANCE: bvx-zalo-app-32f90:asia-southeast1:bvx-postgres
  _SA_EMAIL: bvx-zalo-app-32f90@appspot.gserviceaccount.com
  # TODO: chỉnh lại nếu cần. Có thể dùng Secret Manager thay vì để thẳng ra.
  _ENV_VARS: >-
    PGHOST=/cloudsql/bvx-zalo-app-32f90:asia-southeast1:bvx-postgres,
    PGPORT=5432,
    PGUSER=postgres,
    PGDATABASE=bvx,
    API_KEY=yZtE4ArHtzHmQG6rYLeToeu0ghxAxsTKOVXJzkzGRfQ=

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # 1) Build image từ Dockerfile ở thư mục gốc
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$SHORT_SHA'
      - '.'

  # 2) Push image lên Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$SHORT_SHA'

  # 3) Deploy Cloud Run bằng image vừa push (KHÔNG dùng --source nữa)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - $_SERVICE
      - --project=$PROJECT_ID
      - --region=$_REGION
      - --image=$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$SHORT_SHA
      - --allow-unauthenticated
      - --service-account=$_SA_EMAIL
      - --add-cloudsql-instances=$_DB_INSTANCE
      - --set-env-vars
      - $_ENV_VARS

images:
  - '$_REGION-docker.pkg.dev/$PROJECT_ID/$_REPO/$_SERVICE:$SHORT_SHA'
